# Generated by Django 6.0.3 on 2026-04-17 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_source', models.CharField(choices=[('ats', 'ATS'), ('crm', 'CRM')], max_length=10)),
                ('activity_type', models.CharField(choices=[('note_added', 'Notiz hinzugefügt'), ('call', 'Anruf'), ('meeting', 'Meeting'), ('email_sent', 'E-Mail gesendet'), ('email_received', 'E-Mail empfangen'), ('task', 'Aufgabe'), ('candidate_created', 'Kandidat angelegt'), ('candidate_updated', 'Kandidat aktualisiert'), ('application_created', 'Bewerbung eingegangen'), ('stage_moved', 'Stage verschoben'), ('status_changed', 'Status geändert'), ('ai_scored', 'KI-Scoring'), ('deal_created', 'Deal angelegt'), ('deal_won', 'Deal gewonnen'), ('deal_lost', 'Deal verloren')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Betreff')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fällig am')),
                ('is_done', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by_name', models.CharField(blank=True, max_length=200)),
                ('performed_by_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_to_name', models.CharField(blank=True, max_length=200)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('ats_candidate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ats_application_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('crm_contact_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('crm_company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('crm_deal_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aktivität',
                'verbose_name_plural': 'Aktivitäten',
                'db_table': 'shared_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ats_candidate_id', '-created_at'], name='shared_acti_ats_can_aea1a2_idx'), models.Index(fields=['crm_contact_id', '-created_at'], name='shared_acti_crm_con_886b55_idx')],
            },
        ),
        migrations.CreateModel(
            name='SharedEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_source', models.CharField(choices=[('ats', 'ATS'), ('crm', 'CRM')], max_length=10)),
                ('from_email', models.EmailField(max_length=254, verbose_name='Von')),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to_email', models.EmailField(max_length=254, verbose_name='An')),
                ('to_name', models.CharField(blank=True, max_length=200)),
                ('to_emails', models.TextField(blank=True, verbose_name='Weitere Empfänger (CSV)')),
                ('cc_emails', models.TextField(blank=True, verbose_name='CC (CSV)')),
                ('subject', models.CharField(max_length=500, verbose_name='Betreff')),
                ('body_text', models.TextField(blank=True, verbose_name='Text')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML')),
                ('direction', models.CharField(choices=[('outbound', 'Ausgehend'), ('inbound', 'Eingehend')], default='outbound', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Gesendet'), ('delivered', 'Zugestellt'), ('opened', 'Geöffnet'), ('bounced', 'Bounce'), ('failed', 'Fehlgeschlagen'), ('received', 'Empfangen')], default='draft', max_length=10)),
                ('graph_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('internet_message_id', models.CharField(blank=True, db_index=True, max_length=998)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('mailjet_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('in_reply_to_id', models.UUIDField(blank=True, help_text='UUID einer anderen SharedEmail', null=True, verbose_name='Antwort auf')),
                ('thread_subject', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('sent_by_name', models.CharField(blank=True, max_length=200)),
                ('sent_by_email', models.EmailField(blank=True, max_length=254)),
                ('ats_candidate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ats_application_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('crm_contact_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('crm_deal_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail',
                'verbose_name_plural': 'E-Mails',
                'db_table': 'shared_email',
                'ordering': ['-sent_at', '-created_at'],
                'indexes': [models.Index(fields=['ats_candidate_id', '-created_at'], name='shared_emai_ats_can_837bbf_idx'), models.Index(fields=['crm_contact_id', '-created_at'], name='shared_emai_crm_con_8cc97f_idx'), models.Index(fields=['conversation_id', '-created_at'], name='shared_emai_convers_fabf02_idx')],
            },
        ),
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_source', models.CharField(choices=[('ats', 'ATS'), ('crm', 'CRM')], help_text='App, in der die Notiz erstellt wurde', max_length=10, verbose_name='Quelle')),
                ('text', models.TextField(verbose_name='Notiz')),
                ('note_type', models.CharField(choices=[('general', 'Allgemein'), ('interview', 'Interview'), ('internal', 'Intern'), ('feedback', 'Feedback')], default='general', max_length=20)),
                ('ats_candidate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('crm_contact_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=200, verbose_name='Autor')),
                ('created_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Autor E-Mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notiz',
                'verbose_name_plural': 'Notizen',
                'db_table': 'shared_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ats_candidate_id', '-created_at'], name='shared_note_ats_can_b9a569_idx'), models.Index(fields=['crm_contact_id', '-created_at'], name='shared_note_crm_con_aba35c_idx')],
            },
        ),
    ]
