# Generated by Django 6.0.4 on 2026-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piquano_shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedactivity',
            name='related_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Personen-Name'),
        ),
    ]
