# Generated by Django 6.0.5 on 2026-06-07 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piquano_shared', '0002_add_related_name_to_shared_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vertical',
                'verbose_name_plural': 'Verticals',
                'db_table': 'catalog_vertical',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubFunktion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_funktionen', to='piquano_shared.vertical', verbose_name='Vertical')),
            ],
            options={
                'verbose_name': 'Sub-Funktion',
                'verbose_name_plural': 'Sub-Funktionen',
                'db_table': 'catalog_subfunktion',
                'ordering': ['vertical', 'sort_order', 'name'],
                'unique_together': {('vertical', 'slug')},
            },
        ),
    ]
