# Generated by Django 6.0.5 on 2026-06-07 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piquano_shared', '0003_add_catalog_vertical_subfunktion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('ats_candidate', 'ATS-Kandidat'), ('crm_contact', 'CRM-Kontakt')], help_text='Typ der zugeordneten Person', max_length=20)),
                ('entity_id', models.UUIDField(db_index=True, help_text='UUID des Kandidaten (ATS) oder Kontakts (CRM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_funktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='piquano_shared.subfunktion', verbose_name='Sub-Funktion')),
            ],
            options={
                'verbose_name': 'Katalog-Zuordnung',
                'verbose_name_plural': 'Katalog-Zuordnungen',
                'db_table': 'catalog_assignment',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='catalog_ass_entity__735169_idx')],
                'unique_together': {('entity_type', 'entity_id', 'sub_funktion')},
            },
        ),
    ]
