# Generated by Django 6.0.5 on 2026-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piquano_shared', '0004_add_catalog_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedactivity',
            name='activity_type',
            field=models.CharField(choices=[('note_added', 'Notiz hinzugefügt'), ('call', 'Anruf'), ('meeting', 'Meeting'), ('email_sent', 'E-Mail gesendet'), ('email_received', 'E-Mail empfangen'), ('task', 'Aufgabe'), ('candidate_created', 'Kandidat angelegt'), ('candidate_updated', 'Kandidat aktualisiert'), ('application_created', 'Bewerbung eingegangen'), ('stage_moved', 'Stage verschoben'), ('status_changed', 'Status geändert'), ('ai_scored', 'KI-Scoring'), ('alert_subscribed', 'Projekt-Alert abonniert'), ('deal_created', 'Deal angelegt'), ('deal_won', 'Deal gewonnen'), ('deal_lost', 'Deal verloren')], max_length=30),
        ),
    ]
