# Generated by Django 6.0.5 on 2026-07-03 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piquano_shared', '0005_alter_sharedactivity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app', models.CharField(choices=[('app', 'App'), ('crm', 'CRM'), ('ats', 'ATS'), ('lms', 'LMS'), ('support', 'Support'), ('content', 'Content'), ('core', 'Core'), ('cron', 'Cron-Agent')], max_length=10, verbose_name='App')),
                ('email_type', models.CharField(max_length=80, verbose_name='Typ')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Empfänger')),
                ('subject', models.CharField(max_length=500, verbose_name='Betreff')),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True, verbose_name='Fehler')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML-Inhalt')),
                ('mailjet_message_id', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
            ],
            options={
                'verbose_name': 'E-Mail-Log',
                'verbose_name_plural': 'E-Mail-Logs',
                'db_table': 'email_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='email_log_sent_at_3d6302_idx'), models.Index(fields=['app', '-sent_at'], name='email_log_app_3fd017_idx'), models.Index(fields=['email_type', '-sent_at'], name='email_log_email_t_c4a0c1_idx'), models.Index(fields=['recipient', '-sent_at'], name='email_log_recipie_bb0044_idx')],
            },
        ),
    ]
