# Generated by Django 6.0.3 on 2026-04-12 13:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureToggle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("app_label", models.CharField(max_length=50, verbose_name="App")),
                ("module_name", models.CharField(max_length=100, verbose_name="Modul")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Aktiviert")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert")),
            ],
            options={
                "verbose_name": "Feature-Toggle",
                "verbose_name_plural": "Feature-Toggles",
                "db_table": "piquano_admin_center_featuretoggle",
                "ordering": ["app_label", "module_name"],
                "unique_together": {("app_label", "module_name")},
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("app_label", models.CharField(max_length=50, verbose_name="App")),
                ("module_name", models.CharField(max_length=100, verbose_name="Modul")),
                ("codename", models.CharField(max_length=50, verbose_name="Berechtigung")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="Beschreibung"),
                ),
            ],
            options={
                "verbose_name": "Berechtigung",
                "verbose_name_plural": "Berechtigungen",
                "db_table": "piquano_admin_center_permission",
                "ordering": ["app_label", "module_name", "codename"],
                "unique_together": {("app_label", "module_name", "codename")},
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_granted", models.BooleanField(default=True, verbose_name="Erteilt")),
                ("granted_at", models.DateTimeField(auto_now_add=True, verbose_name="Erteilt am")),
                (
                    "granted_by",
                    models.CharField(blank=True, max_length=150, verbose_name="Erteilt von"),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="piquano_admin_center.permission",
                        verbose_name="Berechtigung",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piquano_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzer-Berechtigung",
                "verbose_name_plural": "Benutzer-Berechtigungen",
                "db_table": "piquano_admin_center_userpermission",
                "ordering": ["user", "permission"],
                "unique_together": {("user", "permission")},
            },
        ),
    ]
